// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArtisanalIntegerServiceClient is the client API for ArtisanalIntegerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtisanalIntegerServiceClient interface {
	NextInt(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ArtisanalInteger, error)
}

type artisanalIntegerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtisanalIntegerServiceClient(cc grpc.ClientConnInterface) ArtisanalIntegerServiceClient {
	return &artisanalIntegerServiceClient{cc}
}

func (c *artisanalIntegerServiceClient) NextInt(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ArtisanalInteger, error) {
	out := new(ArtisanalInteger)
	err := c.cc.Invoke(ctx, "/ArtisanalIntegerService/NextInt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtisanalIntegerServiceServer is the server API for ArtisanalIntegerService service.
// All implementations must embed UnimplementedArtisanalIntegerServiceServer
// for forward compatibility
type ArtisanalIntegerServiceServer interface {
	NextInt(context.Context, *emptypb.Empty) (*ArtisanalInteger, error)
	mustEmbedUnimplementedArtisanalIntegerServiceServer()
}

// UnimplementedArtisanalIntegerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArtisanalIntegerServiceServer struct {
}

func (UnimplementedArtisanalIntegerServiceServer) NextInt(context.Context, *emptypb.Empty) (*ArtisanalInteger, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextInt not implemented")
}
func (UnimplementedArtisanalIntegerServiceServer) mustEmbedUnimplementedArtisanalIntegerServiceServer() {
}

// UnsafeArtisanalIntegerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtisanalIntegerServiceServer will
// result in compilation errors.
type UnsafeArtisanalIntegerServiceServer interface {
	mustEmbedUnimplementedArtisanalIntegerServiceServer()
}

func RegisterArtisanalIntegerServiceServer(s grpc.ServiceRegistrar, srv ArtisanalIntegerServiceServer) {
	s.RegisterService(&ArtisanalIntegerService_ServiceDesc, srv)
}

func _ArtisanalIntegerService_NextInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtisanalIntegerServiceServer).NextInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArtisanalIntegerService/NextInt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtisanalIntegerServiceServer).NextInt(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtisanalIntegerService_ServiceDesc is the grpc.ServiceDesc for ArtisanalIntegerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtisanalIntegerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ArtisanalIntegerService",
	HandlerType: (*ArtisanalIntegerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextInt",
			Handler:    _ArtisanalIntegerService_NextInt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integer.proto",
}
